
2022-12-10 18:26:38,872 INFO: errors [in c:\Users\HP\udacity-class\project samples\2. Fyyur_Web_App_Project-main\Fyyur_Web_App_Project-main\app.py:702]
2022-12-10 18:27:16,189 ERROR: Exception on /venues/create [POST] [in C:\Python\Lib\site-packages\flask\app.py:1741]
Traceback (most recent call last):
  File "C:\Python\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\HP\udacity-class\project samples\2. Fyyur_Web_App_Project-main\Fyyur_Web_App_Project-main\app.py", line 258, in create_venue_submission
    flash(f"{str(message)[2:len(str(message))-2]}!", category="danger")
  File "C:\Python\Lib\site-packages\flask\helpers.py", line 361, in flash
    session["_flashes"] = flashes
    ~~~~~~~^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\flask\sessions.py", line 98, in _fail
    raise RuntimeError(
RuntimeError: The session is unavailable because no secret key was set.  Set the secret_key on the application to something unique and secret.
2022-12-10 18:29:07,082 ERROR: Exception on /artists/create [POST] [in C:\Python\Lib\site-packages\flask\app.py:1741]
Traceback (most recent call last):
  File "C:\Python\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\HP\udacity-class\project samples\2. Fyyur_Web_App_Project-main\Fyyur_Web_App_Project-main\app.py", line 531, in create_artist_submission
    flash(f"{str(message)[2:len(str(message))-2]}!", category="danger")
  File "C:\Python\Lib\site-packages\flask\helpers.py", line 361, in flash
    session["_flashes"] = flashes
    ~~~~~~~^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\flask\sessions.py", line 98, in _fail
    raise RuntimeError(
RuntimeError: The session is unavailable because no secret key was set.  Set the secret_key on the application to something unique and secret.
2022-12-10 18:42:34,568 ERROR: Exception on /venues/create [POST] [in C:\Python\Lib\site-packages\flask\app.py:1741]
Traceback (most recent call last):
  File "C:\Python\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\HP\udacity-class\project samples\2. Fyyur_Web_App_Project-main\Fyyur_Web_App_Project-main\app.py", line 258, in create_venue_submission
    flash(f"{str(message)[2:len(str(message))-2]}!", category="danger")
  File "C:\Python\Lib\site-packages\flask\helpers.py", line 361, in flash
    session["_flashes"] = flashes
    ~~~~~~~^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\flask\sessions.py", line 98, in _fail
    raise RuntimeError(
RuntimeError: The session is unavailable because no secret key was set.  Set the secret_key on the application to something unique and secret.
2022-12-10 18:43:09,890 ERROR: Exception on /venues/create [POST] [in C:\Python\Lib\site-packages\flask\app.py:1741]
Traceback (most recent call last):
  File "C:\Python\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\HP\udacity-class\project samples\2. Fyyur_Web_App_Project-main\Fyyur_Web_App_Project-main\app.py", line 258, in create_venue_submission
    flash(f"{str(message)[2:len(str(message))-2]}!", category="danger")
  File "C:\Python\Lib\site-packages\flask\helpers.py", line 361, in flash
    session["_flashes"] = flashes
    ~~~~~~~^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\flask\sessions.py", line 98, in _fail
    raise RuntimeError(
RuntimeError: The session is unavailable because no secret key was set.  Set the secret_key on the application to something unique and secret.
2022-12-10 18:44:28,708 ERROR: Exception on /venues/create [POST] [in C:\Python\Lib\site-packages\flask\app.py:1741]
Traceback (most recent call last):
  File "C:\Python\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\HP\udacity-class\project samples\2. Fyyur_Web_App_Project-main\Fyyur_Web_App_Project-main\app.py", line 258, in create_venue_submission
    flash(f"{str(message)[2:len(str(message))-2]}!", category="danger")
  File "C:\Python\Lib\site-packages\flask\helpers.py", line 361, in flash
    session["_flashes"] = flashes
    ~~~~~~~^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\flask\sessions.py", line 98, in _fail
    raise RuntimeError(
RuntimeError: The session is unavailable because no secret key was set.  Set the secret_key on the application to something unique and secret.
2022-12-10 18:57:54,048 ERROR: Exception on /artists/create [POST] [in C:\Python\Lib\site-packages\flask\app.py:1741]
Traceback (most recent call last):
  File "C:\Python\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\HP\udacity-class\project samples\2. Fyyur_Web_App_Project-main\Fyyur_Web_App_Project-main\app.py", line 531, in create_artist_submission
    flash(f"{str(message)[2:len(str(message))-2]}!", category="danger")
  File "C:\Python\Lib\site-packages\flask\helpers.py", line 361, in flash
    session["_flashes"] = flashes
    ~~~~~~~^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\flask\sessions.py", line 98, in _fail
    raise RuntimeError(
RuntimeError: The session is unavailable because no secret key was set.  Set the secret_key on the application to something unique and secret.
2022-12-10 18:58:09,553 ERROR: Exception on /artists/create [POST] [in C:\Python\Lib\site-packages\flask\app.py:1741]
Traceback (most recent call last):
  File "C:\Python\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\HP\udacity-class\project samples\2. Fyyur_Web_App_Project-main\Fyyur_Web_App_Project-main\app.py", line 531, in create_artist_submission
    flash(f"{str(message)[2:len(str(message))-2]}!", category="danger")
  File "C:\Python\Lib\site-packages\flask\helpers.py", line 361, in flash
    session["_flashes"] = flashes
    ~~~~~~~^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\flask\sessions.py", line 98, in _fail
    raise RuntimeError(
RuntimeError: The session is unavailable because no secret key was set.  Set the secret_key on the application to something unique and secret.
2022-12-10 18:58:17,976 ERROR: Exception on /artists/create [POST] [in C:\Python\Lib\site-packages\flask\app.py:1741]
Traceback (most recent call last):
  File "C:\Python\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\HP\udacity-class\project samples\2. Fyyur_Web_App_Project-main\Fyyur_Web_App_Project-main\app.py", line 531, in create_artist_submission
    flash(f"{str(message)[2:len(str(message))-2]}!", category="danger")
  File "C:\Python\Lib\site-packages\flask\helpers.py", line 361, in flash
    session["_flashes"] = flashes
    ~~~~~~~^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\flask\sessions.py", line 98, in _fail
    raise RuntimeError(
RuntimeError: The session is unavailable because no secret key was set.  Set the secret_key on the application to something unique and secret.
2022-12-10 18:59:05,290 ERROR: Exception on /artists/create [POST] [in C:\Python\Lib\site-packages\flask\app.py:1741]
Traceback (most recent call last):
  File "C:\Python\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\HP\udacity-class\project samples\2. Fyyur_Web_App_Project-main\Fyyur_Web_App_Project-main\app.py", line 531, in create_artist_submission
    flash(f"{str(message)[2:len(str(message))-2]}!", category="danger")
  File "C:\Python\Lib\site-packages\flask\helpers.py", line 361, in flash
    session["_flashes"] = flashes
    ~~~~~~~^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\flask\sessions.py", line 98, in _fail
    raise RuntimeError(
RuntimeError: The session is unavailable because no secret key was set.  Set the secret_key on the application to something unique and secret.
2022-12-10 18:59:10,269 ERROR: Exception on /artists/create [POST] [in C:\Python\Lib\site-packages\flask\app.py:1741]
Traceback (most recent call last):
  File "C:\Python\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\HP\udacity-class\project samples\2. Fyyur_Web_App_Project-main\Fyyur_Web_App_Project-main\app.py", line 531, in create_artist_submission
    flash(f"{str(message)[2:len(str(message))-2]}!", category="danger")
  File "C:\Python\Lib\site-packages\flask\helpers.py", line 361, in flash
    session["_flashes"] = flashes
    ~~~~~~~^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\flask\sessions.py", line 98, in _fail
    raise RuntimeError(
RuntimeError: The session is unavailable because no secret key was set.  Set the secret_key on the application to something unique and secret.
2022-12-10 18:59:25,667 ERROR: Exception on /artists/create [POST] [in C:\Python\Lib\site-packages\flask\app.py:1741]
Traceback (most recent call last):
  File "C:\Python\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\HP\udacity-class\project samples\2. Fyyur_Web_App_Project-main\Fyyur_Web_App_Project-main\app.py", line 531, in create_artist_submission
    flash(f"{str(message)[2:len(str(message))-2]}!", category="danger")
  File "C:\Python\Lib\site-packages\flask\helpers.py", line 361, in flash
    session["_flashes"] = flashes
    ~~~~~~~^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\flask\sessions.py", line 98, in _fail
    raise RuntimeError(
RuntimeError: The session is unavailable because no secret key was set.  Set the secret_key on the application to something unique and secret.
2022-12-10 19:03:49,237 ERROR: Exception on /venues/create [POST] [in C:\Python\Lib\site-packages\flask\app.py:1741]
Traceback (most recent call last):
  File "C:\Python\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\HP\udacity-class\project samples\2. Fyyur_Web_App_Project-main\Fyyur_Web_App_Project-main\app.py", line 258, in create_venue_submission
    flash(f"{str(message)[2:len(str(message))-2]}!", category="danger")
  File "C:\Python\Lib\site-packages\flask\helpers.py", line 361, in flash
    session["_flashes"] = flashes
    ~~~~~~~^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\flask\sessions.py", line 98, in _fail
    raise RuntimeError(
RuntimeError: The session is unavailable because no secret key was set.  Set the secret_key on the application to something unique and secret.
2022-12-10 19:11:04,349 ERROR: Exception on /venues/create [POST] [in C:\Python\Lib\site-packages\flask\app.py:1741]
Traceback (most recent call last):
  File "C:\Python\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\HP\udacity-class\project samples\2. Fyyur_Web_App_Project-main\Fyyur_Web_App_Project-main\app.py", line 258, in create_venue_submission
    flash(f"{str(message)[2:len(str(message))-2]}!", category="danger")
  File "C:\Python\Lib\site-packages\flask\helpers.py", line 361, in flash
    session["_flashes"] = flashes
    ~~~~~~~^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\flask\sessions.py", line 98, in _fail
    raise RuntimeError(
RuntimeError: The session is unavailable because no secret key was set.  Set the secret_key on the application to something unique and secret.
2022-12-10 19:11:18,952 INFO: errors [in c:\Users\HP\udacity-class\project samples\2. Fyyur_Web_App_Project-main\Fyyur_Web_App_Project-main\app.py:702]
2022-12-10 19:11:24,355 ERROR: Exception on /venues/create [POST] [in C:\Python\Lib\site-packages\flask\app.py:1741]
Traceback (most recent call last):
  File "C:\Python\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\HP\udacity-class\project samples\2. Fyyur_Web_App_Project-main\Fyyur_Web_App_Project-main\app.py", line 258, in create_venue_submission
    flash(f"{str(message)[2:len(str(message))-2]}!", category="danger")
  File "C:\Python\Lib\site-packages\flask\helpers.py", line 361, in flash
    session["_flashes"] = flashes
    ~~~~~~~^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\flask\sessions.py", line 98, in _fail
    raise RuntimeError(
RuntimeError: The session is unavailable because no secret key was set.  Set the secret_key on the application to something unique and secret.
2022-12-10 19:12:31,025 ERROR: Exception on /venues/create [POST] [in C:\Python\Lib\site-packages\flask\app.py:1741]
Traceback (most recent call last):
  File "C:\Python\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\HP\udacity-class\project samples\2. Fyyur_Web_App_Project-main\Fyyur_Web_App_Project-main\app.py", line 258, in create_venue_submission
    flash(f"{str(message)[2:len(str(message))-2]}!", category="danger")
  File "C:\Python\Lib\site-packages\flask\helpers.py", line 361, in flash
    session["_flashes"] = flashes
    ~~~~~~~^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\flask\sessions.py", line 98, in _fail
    raise RuntimeError(
RuntimeError: The session is unavailable because no secret key was set.  Set the secret_key on the application to something unique and secret.
2022-12-10 19:14:32,363 ERROR: Exception on /venues/create [POST] [in C:\Python\Lib\site-packages\flask\app.py:1741]
Traceback (most recent call last):
  File "C:\Python\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\HP\udacity-class\project samples\2. Fyyur_Web_App_Project-main\Fyyur_Web_App_Project-main\app.py", line 258, in create_venue_submission
    flash(f"{str(message)[2:len(str(message))-2]}!", category="danger")
  File "C:\Python\Lib\site-packages\flask\helpers.py", line 361, in flash
    session["_flashes"] = flashes
    ~~~~~~~^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\flask\sessions.py", line 98, in _fail
    raise RuntimeError(
RuntimeError: The session is unavailable because no secret key was set.  Set the secret_key on the application to something unique and secret.
2022-12-10 19:14:36,569 ERROR: Exception on /venues/create [POST] [in C:\Python\Lib\site-packages\flask\app.py:1741]
Traceback (most recent call last):
  File "C:\Python\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\HP\udacity-class\project samples\2. Fyyur_Web_App_Project-main\Fyyur_Web_App_Project-main\app.py", line 258, in create_venue_submission
    flash(f"{str(message)[2:len(str(message))-2]}!", category="danger")
  File "C:\Python\Lib\site-packages\flask\helpers.py", line 361, in flash
    session["_flashes"] = flashes
    ~~~~~~~^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\flask\sessions.py", line 98, in _fail
    raise RuntimeError(
RuntimeError: The session is unavailable because no secret key was set.  Set the secret_key on the application to something unique and secret.
2022-12-10 19:15:27,251 ERROR: Exception on /venues/create [POST] [in C:\Python\Lib\site-packages\flask\app.py:1741]
Traceback (most recent call last):
  File "C:\Python\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\HP\udacity-class\project samples\2. Fyyur_Web_App_Project-main\Fyyur_Web_App_Project-main\app.py", line 258, in create_venue_submission
    flash(f"{str(message)[2:len(str(message))-2]}!", category="danger")
  File "C:\Python\Lib\site-packages\flask\helpers.py", line 361, in flash
    session["_flashes"] = flashes
    ~~~~~~~^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\flask\sessions.py", line 98, in _fail
    raise RuntimeError(
RuntimeError: The session is unavailable because no secret key was set.  Set the secret_key on the application to something unique and secret.
2022-12-10 19:16:35,203 ERROR: Exception on /venues/create [POST] [in C:\Python\Lib\site-packages\flask\app.py:1741]
Traceback (most recent call last):
  File "C:\Python\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\HP\udacity-class\project samples\2. Fyyur_Web_App_Project-main\Fyyur_Web_App_Project-main\app.py", line 258, in create_venue_submission
    flash(f"{str(message)[2:len(str(message))-2]}!", category="danger")
  File "C:\Python\Lib\site-packages\flask\helpers.py", line 361, in flash
    session["_flashes"] = flashes
    ~~~~~~~^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\flask\sessions.py", line 98, in _fail
    raise RuntimeError(
RuntimeError: The session is unavailable because no secret key was set.  Set the secret_key on the application to something unique and secret.
2022-12-10 19:16:44,273 INFO: errors [in c:\Users\HP\udacity-class\project samples\2. Fyyur_Web_App_Project-main\Fyyur_Web_App_Project-main\app.py:702]
2022-12-10 19:21:25,566 INFO: errors [in c:\Users\HP\udacity-class\project samples\2. Fyyur_Web_App_Project-main\Fyyur_Web_App_Project-main\app.py:702]
2022-12-10 19:23:11,139 INFO: errors [in c:\Users\HP\udacity-class\project samples\2. Fyyur_Web_App_Project-main\Fyyur_Web_App_Project-main\app.py:702]
2022-12-10 19:28:37,654 INFO: errors [in c:\Users\HP\udacity-class\project samples\2. Fyyur_Web_App_Project-main\Fyyur_Web_App_Project-main\app.py:702]
